### ISSUE TITLE
license file missing in the source code

### ISSUE THREAD

**Issue by jayramr** [pwwang/pyparam#15]
Hi 

License file missing in the source code / tarball which results unable to build this  python module on conda-forge

Refer -> https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually

Please update/fix the same in the code

**Comment by pwwang** [comment]
Added at f18f1996300841b88d86fccc8738f44da46de949

Need a release for it?

**Comment by jayramr** [comment]
Thanks , if you can include this on existing or newer release would be fine :)

**Comment by pwwang** [comment]
Included in [v0.5.1](https://github.com/pwwang/pyparam/releases/tag/0.5.1)
