### ISSUE TITLE
feature-request: add support for generating help / usage string

### ISSUE THREAD

**Issue by jonEbird** [pwwang/pyparam#17]
Similar to the argparse support for generating the usage / help statement, I'm finding myself needing to generate these messages to use in different ways: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.format_usage

Do you think we can add something like this?

**Comment by pwwang** [comment]
Sorry, this package is deprecated. Try [argx](https://github.com/pwwang/argx) instead.

**Comment by jonEbird** [comment]
That's fair, I didn't realize it was deprecated. I briefly checked out argx but didn't see shell completion support over there which is why I was using pyparam in the first place. May I ask if I merely missed that or if it's planned for argx? Or yet another suggestion for providing shell completion? Thank you.

**Comment by pwwang** [comment]
Since argx is compatible with argparse. Those packages that provide completion functionality based on argparse would also work for argx as well. Here is an example:

https://github.com/GeekLiB/argcomplete/
